name: Deploy Backend to TheTeleporter

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: [self-hosted, Linux, X64]
    name: Backend Deployment
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # - name: Set up .NET
      #   uses: actions/setup-dotnet@v3
      #   with:
      #     dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release

      - name: Publish the project
        run: dotnet publish --configuration Release --output ~/deploy/desapps25c1/backend

#      - name: Restart Backend service
#        run: sudo systemctl restart desapps25c1-backend.service